name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run InfluxDb container
        run: |
          docker run \
            -p 127.0.0.1:8086:8086 \
            --name influxdb2 \
            --detach \
            influxdb

      - name: Setup the container
        run: |
          docker exec influxdb2 influx setup \
               --username influx \
               --password password \
               --org home \
               --bucket octopus

      - name: Create an API key
        run: |
          docker exec influxdb2 influx auth create \
               --write-buckets

      - name: Install the package
        run: pip install .

      - name: Run octopus-influx
        run: octopus-influx
