name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the package
        run: pip install .

      - name: Run InfluxDb container
        run: |
          docker run \
            -p 8086:8086 \
            -e DOCKER_INFLUXDB_INIT_USERNAME=github \
            -e DOCKER_INFLUXDB_INIT_PASSWORD=password \
            -e DOCKER_INFLUXDB_INIT_ORG=home \
            -e DOCKER_INFLUXDB_INIT_BUCKET=octopus \
            -e DOCKER_INFLUXDB_INIT_MODE=setup \
            --name influx_container \
            --detach \
            influxdb:latest
          docker exec influx_container influx auth create \
               --write-buckets
          docker logs influx_container
